import { Platform, StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const createStyles = (colorScheme: 'light' | 'dark') =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors[colorScheme].background },
    bannerWrapper: {
      position: 'relative',
      height: 260,
      backgroundColor: colorScheme === 'dark' ? '#1E1E1E' : '#eff6ff',
    },
    bannerImage: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
    bannerPlaceholderEmojiWrap: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bannerPlaceholderEmoji: { fontSize: 96, opacity: 0.92 },
    venueCreditFooter: {
      marginTop: 14,
      marginBottom: 4,
      paddingTop: 12,
      paddingHorizontal: 2,
      borderTopWidth: 1,
      borderTopColor: Colors[colorScheme].border,
    },
    venueCreditFooterText: {
      color: Colors[colorScheme].mutedText,
      fontSize: 11,
      lineHeight: 15,
      textAlign: 'center',
    },
    bannerShade: { position: 'absolute', left: 0, right: 0, bottom: 0, top: 0 },
    headerWrap: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 30,
      backgroundColor: 'transparent',
      paddingBottom: 8,
      marginBottom: 12,
    },
    fab: {
      position: 'absolute',
      right: 16,
      bottom: 24,
      backgroundColor: 'rgba(17,24,39,0.92)',
      borderRadius: 24,
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      zIndex: 40,
    },
    fabText: { color: '#fff', fontWeight: '700' },

    voteWrapper: {
      marginTop: -16,
      paddingHorizontal: 16,
      paddingTop: 2,
      paddingBottom: 0,
      marginBottom: 24,
    },
    voteBar: {
      position: 'relative',
      height: 38,
      borderRadius: 12,
      backgroundColor: Colors[colorScheme].border,
      overflow: 'hidden',
      flexDirection: 'row',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 3px 6px rgba(0, 0, 0, 0.15)' }
        : {
            shadowColor: '#000',
            shadowOpacity: 0.15,
            shadowRadius: 6,
            shadowOffset: { width: 0, height: 3 },
          }),
      elevation: 3,
      marginBottom: 8,
    },
    voteBarDisabled: { opacity: 0.65 },
    // RSVP sheet styles
    sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.4)' },
    sheetContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: Colors[colorScheme].card,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 24,
    },
    sheetHandleBar: {
      alignSelf: 'center',
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: Colors[colorScheme].border,
      marginBottom: 10,
    },
    sheetHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
    sheetTitle: { fontSize: 16, fontWeight: '700', color: Colors[colorScheme].text },
    sheetPrimaryBtn: {
      marginTop: 4,
      backgroundColor: Colors[colorScheme].tint,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    sheetBtnOn: { backgroundColor: '#ef4444' },
    sheetPrimaryBtnText: { color: '#fff', fontWeight: '700' },
    sheetNote: { marginTop: 10, color: Colors[colorScheme].mutedText },
    sheetStatsRow: { marginTop: 16, flexDirection: 'row', gap: 10 },
    sheetStatCard: {
      flex: 1,
      backgroundColor: Colors[colorScheme].surface,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: Colors[colorScheme].border,
    },
    sheetStatValue: { fontSize: 18, fontWeight: '800', color: Colors[colorScheme].text },
    sheetStatLabel: {
      marginTop: 2,
      fontSize: 12,
      color: Colors[colorScheme].mutedText,
      fontWeight: '600',
    },
    voteFill: {
      height: '100%',
      overflow: 'hidden',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    voteFillA: {
      backgroundColor: '#2563EB',
      borderTopLeftRadius: 12,
      borderBottomLeftRadius: 12,
    },
    voteFillB: {
      backgroundColor: '#10B981',
      borderTopRightRadius: 12,
      borderBottomRightRadius: 12,
    },
    voteFillHighlight: { ...StyleSheet.absoluteFillObject, pointerEvents: 'none' },
    voteLabelLayer: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
    },
    voteLabelCell: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    voteLabelCellLeft: { alignItems: 'center', marginRight: 16 },
    voteLabelCellRight: { alignItems: 'center', marginLeft: 16 },
    voteLabelCenter: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
    },
    voteLabelText: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },
    voteLabelTextDim: { opacity: 0.7 },
    voteTextInside: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 14,
      textAlign: 'center',
    },
    voteLabelsAbove: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      paddingHorizontal: 8,
      minHeight: 32,
    },
    voteLabelAboveLeft: {
      flex: 1,
      alignItems: 'flex-start',
      marginRight: 16,
    },
    voteLabelAboveRight: {
      flex: 1,
      alignItems: 'flex-end',
      marginLeft: 16,
    },
    voteLabelWinning: {
      borderWidth: 2,
      borderColor: Colors[colorScheme].tint,
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
      backgroundColor: `${Colors[colorScheme].tint}10`,
    },
    voteLabelAboveText: {
      color: Colors[colorScheme].mutedText,
      fontWeight: '600',
      fontSize: 12,
    },
    voteLabelWinningText: {
      color: Colors[colorScheme].tint,
      fontWeight: '700',
    },
    voteCaptionInline: {
      color: 'rgba(255,255,255,0.85)',
      fontWeight: '700',
      fontSize: 12,
      textAlign: 'center',
    },
    voteCaptionBelow: {
      marginTop: 0,
      marginBottom: 16,
      textAlign: 'center',
      color: Colors[colorScheme].mutedText,
      fontWeight: '600',
      fontSize: 13,
      paddingHorizontal: 12,
    },
    voteTouchLayer: { ...StyleSheet.absoluteFillObject, flexDirection: 'row' },
    voteTouchHalf: { flex: 1 },
    voteFloatPill: {
      position: 'absolute',
      top: -18,
      backgroundColor: Colors[colorScheme].card,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 2px 6px rgba(15, 23, 42, 0.12)' }
        : {
            shadowColor: '#0f172a',
            shadowOpacity: 0.12,
            shadowRadius: 6,
            shadowOffset: { width: 0, height: 2 },
          }),
      elevation: 2,
    },
    voteFloatLeft: { left: 28 },
    voteFloatRight: { right: 28 },
    voteFloatText: {
      color: Colors[colorScheme].text,
      fontWeight: '700',
      fontSize: 12,
      textAlign: 'center',
    },

    teamLinkButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors[colorScheme].surface,
      padding: 8,
      borderRadius: 8,
      marginVertical: 4,
    },
    teamLinkAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      marginRight: 8,
    },
    teamLinkName: {
      flex: 1,
      fontWeight: '600',
    },

    // Enhanced team card styles for bottom section (now using inline styles)
    teamLinkButtonEnhanced: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      minHeight: 160,
    },
    teamAvatarContainer: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
      borderWidth: 2,
    },
    teamLinkAvatarLarge: {
      width: 68,
      height: 68,
      borderRadius: 34,
    },
    teamIconPlaceholder: {
      width: 68,
      height: 68,
      borderRadius: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teamNameLarge: {
      fontWeight: '700',
      fontSize: 16,
      textAlign: 'center',
      marginHorizontal: 4,
    },
    viewAllButton: {
      backgroundColor: Colors[colorScheme].surface,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 16,
    },
    viewAllButtonText: {
      fontWeight: '600',
    },

    bannerTopRow: {
      position: 'absolute',
      left: 16,
      right: 16,
      top: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    bannerTopRightRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    bannerBottomRow: {
      position: 'absolute',
      left: 16,
      right: 16,
      bottom: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    bannerBottomLeft: { flexDirection: 'column', gap: 8, maxWidth: '70%' },
    dateChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colorScheme === 'dark' ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.9)',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    dateChipText: { fontWeight: '700', color: Colors[colorScheme].text, fontSize: 13 },
    dateChipTime: { fontWeight: '600', color: Colors[colorScheme].tint, fontSize: 13 },
    statusChip: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colorScheme === 'dark' ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.92)',
    },
    statusUpcoming: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.3)' : 'rgba(219,234,254,0.95)',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.5)' : '#bfdbfe',
    },
    statusLive: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(239,68,68,0.3)' : 'rgba(254,226,226,0.95)',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(239,68,68,0.5)' : '#fecaca',
    },
    statusFinal: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(107,114,128,0.3)' : 'rgba(229,231,235,0.95)',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(107,114,128,0.5)' : '#d1d5db',
    },
    statusText: { fontWeight: '800', color: Colors[colorScheme].text },
    liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444' },
    rsvpChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: 'rgba(255,255,255,0.9)',
      borderWidth: 1,
      borderColor: '#BFDBFE',
    },
    rsvpOn: { backgroundColor: '#c7d2fe', borderColor: '#818cf8' },
    rsvpDisabled: { opacity: 0.6 },
    rsvpText: { fontWeight: '700', color: Colors[colorScheme].tint },
    rsvpTextOn: { color: Colors[colorScheme].text },
    rsvpTopInline: { paddingHorizontal: 10, paddingVertical: 6 },
    rsvpTextInline: { fontSize: 13 },
    finalChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(254,226,226,0.9)',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    finalText: { color: '#991b1b', fontWeight: '700' },
    circleButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colorScheme === 'dark' ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.92)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    watchingActive: { backgroundColor: '#c7d2fe' },
    watchingEmoji: { fontSize: 16, lineHeight: 20 },
    scroll: { flex: 1 },
    content: { paddingHorizontal: 16, paddingTop: 24 },
    loadingBox: { paddingVertical: 24, alignItems: 'center' },
    errorBox: {
      padding: 16,
      borderRadius: 12,
      backgroundColor: colorScheme === 'dark' ? 'rgba(239,68,68,0.2)' : '#fee2e2',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(239,68,68,0.4)' : '#fecaca',
      marginBottom: 16,
    },
    errorText: {
      color: colorScheme === 'dark' ? '#fca5a5' : '#991b1b',
      fontWeight: '600',
      marginBottom: 8,
    },
    retryBtn: {
      alignSelf: 'flex-start',
      backgroundColor: '#DC2626',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
    },
    retryText: { color: 'white', fontWeight: '700' },
    title: {
      fontSize: 28,
      fontWeight: '900',
      color: Colors[colorScheme].text,
      marginTop: 8,
      marginBottom: 6,
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginBottom: 12,
      width: '100%',
      paddingRight: 6,
    },
    locationText: {
      color: Colors[colorScheme].text,
      fontWeight: '600',
      textDecorationLine: 'underline',
      flex: 1,
      flexShrink: 1,
      lineHeight: 20,
    },
    actionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
    secondaryActionsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    storyHelpText: {
      fontSize: 12,
      color: Colors[colorScheme].mutedText,
      fontWeight: '600',
      marginTop: 4,
      width: '100%',
      textAlign: 'center',
    },
    preciseBanner: {
      flexDirection: 'row',
      gap: 12,
      borderRadius: 12,
      borderWidth: 1,
      padding: 12,
      marginBottom: 16,
      alignItems: 'flex-start',
    },
    preciseBannerTitle: { fontWeight: '700', fontSize: 14, color: '#92400E' },
    preciseBannerText: { fontSize: 13, color: '#92400E', marginTop: 2, marginBottom: 8 },
    preciseBannerActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    preciseBannerLink: { fontSize: 13, color: '#92400E' },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderRadius: 12,
      backgroundColor: Colors[colorScheme].surface,
      paddingVertical: 12,
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: Colors[colorScheme].border,
    },
    actionBtnDisabled: { opacity: 0.6 },
    actionText: { fontWeight: '700', color: Colors[colorScheme].text },
    storyCountdown: { fontSize: 12, textAlign: 'center', marginTop: -8, marginBottom: 12 },
    tabRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
      backgroundColor: colorScheme === 'dark' ? Colors[colorScheme].surface : '#eef2ff',
      borderRadius: 999,
      padding: 4,
    },
    tabRowWrap: { marginBottom: 12, paddingHorizontal: 8 },
    tabRowCapsule: {
      flexDirection: 'row',
      backgroundColor: colorScheme === 'dark' ? Colors[colorScheme].surface : '#eef2ff',
      borderRadius: 999,
      padding: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBtnCapsule: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      marginHorizontal: 4,
    },
    tabBtnCapsuleOn: {
      backgroundColor: Colors[colorScheme].card,
      borderWidth: 1,
      borderColor: Colors[colorScheme].tint,
    },
    tabBtn: { flex: 1, borderRadius: 999, alignItems: 'center', paddingVertical: 8 },
    tabBtnOn: {
      backgroundColor: Colors[colorScheme].card,
      borderWidth: 1,
      borderColor: Colors[colorScheme].tint,
    },
    tabText: { fontWeight: '600', color: Colors[colorScheme].mutedText },
    tabTextOn: { color: Colors[colorScheme].tint },
    section: { marginBottom: 24 },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    addPostButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: Colors[colorScheme].surface,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
          }),
      elevation: 2,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors[colorScheme].text,
      marginBottom: 8,
    },
    sectionSubtitle: { color: Colors[colorScheme].mutedText, fontWeight: '600' },
    sectionHelper: { marginBottom: 12 },
    bodyText: { color: Colors[colorScheme].text, fontSize: 16, lineHeight: 24 },
    muted: { color: Colors[colorScheme].mutedText, fontStyle: 'italic' },
    statRow: { flexDirection: 'row', gap: 12, marginTop: 16, marginBottom: 20 },
    statCard: {
      flex: 1,
      backgroundColor: Colors[colorScheme].surface,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      gap: 6,
    },
    statValue: { fontSize: 20, fontWeight: '800', color: Colors[colorScheme].text },
    statLabel: { color: Colors[colorScheme].mutedText, fontWeight: '600' },
    editResultButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
      marginTop: 12,
      marginBottom: 20,
    },
    editResultButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
    editResultBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    editResultModal: {
      width: '100%',
      maxWidth: 340,
      borderRadius: 20,
      padding: 24,
    },
    editResultTitle: { fontSize: 18, fontWeight: '800', marginBottom: 20, textAlign: 'center' },
    editResultRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 6 },
    editResultLabel: { flex: 1, fontWeight: '600', fontSize: 14 },
    editResultInput: {
      width: 64,
      borderWidth: 2,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'center',
    },
    editResultVs: { textAlign: 'center', marginVertical: 8, fontWeight: '600' },
    editResultActions: { flexDirection: 'row', gap: 12, marginTop: 24 },
    editResultCancelBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 2,
      alignItems: 'center',
    },
    editResultCancelText: { fontWeight: '600' },
    editResultSubmitBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center' },
    editResultSubmitText: { color: '#FFFFFF', fontWeight: '700' },
    teamList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    teamPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: '#e0f2fe',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    teamPillText: { fontWeight: '700', color: '#0c4a6e' },
    mediaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    mediaThumb: {
      width: '31%',
      aspectRatio: 1,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: '#e2e8f0',
    },
    mediaThumbContent: { flex: 1 },
    mediaVideo: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    storiesWrap: { marginTop: 16, marginBottom: 8 },
    storiesRow: { paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
    storyItem: {
      width: 120,
      height: 200,
      borderRadius: 16,
      overflow: 'hidden',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.25)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.25,
            shadowRadius: 8,
          }),
      elevation: 6,
    },
    storyItemGap: { marginLeft: 0 },
    storyTile: {
      flex: 1,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: '#121212',
      borderWidth: 0,
    },
    storyItemSeen: { opacity: 0.5, transform: [{ scale: 0.95 }] },
    storyTileCountdown: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 8,
      backgroundColor: '#121212',
    },
    storyTileLabel: { color: '#cbd5e1', fontWeight: '700', fontSize: 12, marginBottom: 6 },
    storyTileTime: { color: '#ffffff', fontWeight: '900', fontSize: 16 },
    storyLiveRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    storyLiveText: { color: '#ffffff', fontWeight: '900' },
    storyFinalText: { color: '#e5e7eb', fontWeight: '800' },
    storyThumb: { flex: 1 },
    storyThumbVideo: {
      // NO alignItems/justifyContent here. They centered the poster instead of
      // letting it fill: `alignItems: 'center'` stops the child stretching on
      // the cross axis, so the <Image> (which only carries flex: 1) resolved to
      // width 0 and was invisible — leaving this dark background + the play icon
      // showing through. That is the "video stories are black tiles" bug, and it
      // hit the VideoFirstFrame fallback identically, so neither path could ever
      // draw. They were vestigial anyway: the play icon centers itself inside
      // its own absoluteFill wrapper.
      backgroundColor: 'rgba(2,6,23,0.85)',
    },
    storySeenOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2,6,23,0.25)' },
    storyItemExpired: { opacity: 0.6 },
    storyExpiredOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.6)',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    storyExpiredLabel: { color: '#fff', fontWeight: '800', fontSize: 12 },
    storyExpiredHint: { color: 'rgba(255,255,255,0.8)', fontSize: 10 },
    storyCountdownBadge: {
      position: 'absolute',
      bottom: 6,
      left: 6,
      right: 6,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      backgroundColor: 'rgba(0,0,0,0.6)',
      paddingVertical: 4,
      paddingHorizontal: 6,
      borderRadius: 8,
    },
    storyCountdownText: { color: '#fff', fontSize: 10, fontWeight: '700' },
    verticalFeedPreview: {
      marginTop: 16,
      borderRadius: 20,
      overflow: 'hidden',
      minHeight: 220,
      backgroundColor: '#121212',
    },
    verticalFeedImage: { ...StyleSheet.absoluteFillObject },
    verticalFeedShade: { ...StyleSheet.absoluteFillObject },
    verticalFeedContent: {
      position: 'absolute',
      left: 24,
      right: 24,
      bottom: 24,
      gap: 6,
      maxWidth: 260,
    },
    verticalFeedBadge: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(37,99,235,0.9)',
      marginBottom: 12,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 6px 16px rgba(15, 23, 42, 0.25)' }
        : {
            shadowColor: '#0f172a',
            shadowOpacity: 0.25,
            shadowOffset: { width: 0, height: 6 },
            shadowRadius: 16,
          }),
      elevation: 4,
    },
    verticalFeedTitle: { color: '#ffffff', fontWeight: '800', fontSize: 20, marginBottom: 6 },
    verticalFeedSubtitle: { color: '#cbd5f5', fontWeight: '600', fontSize: 13, marginTop: 2 },
    verticalFeedActions: { marginTop: 12, flexDirection: 'row', justifyContent: 'flex-end' },
    postCtaBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#2563EB',
      borderRadius: 999,
      paddingHorizontal: 18,
      paddingVertical: 10,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 4px 12px rgba(30, 58, 138, 0.25)' }
        : {
            shadowColor: '#1e3a8a',
            shadowOpacity: 0.25,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
          }),
      elevation: 4,
    },
    postCtaBtnDisabled: { opacity: 0.6 },
    postCtaText: { color: '#ffffff', fontWeight: '700' },
    verticalFeedModal: { flex: 1, backgroundColor: '#020617' },
    viewerBackDrop: {
      flex: 1,
      backgroundColor: 'rgba(15,23,42,0.9)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    viewerContent: { width: '90%', aspectRatio: 3 / 4, maxHeight: '80%' },
    viewerMedia: { width: '100%', height: '100%', borderRadius: 16 },
    // Team logos banner overlay styles
    teamLogosOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 120,
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    teamMatchup: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.7)',
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 16,
      gap: 12,
    },
    teamSideInBanner: {
      alignItems: 'center',
      gap: 4,
      minWidth: 80,
    },
    teamLogoInBanner: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.4)',
      overflow: 'hidden',
    },
    teamLogoImage: {
      width: '100%',
      height: '100%',
      borderRadius: 30,
    },
    teamLogoEmojiInBanner: {
      fontSize: 28,
    },
    teamNameInBanner: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'center',
    },
    teamLabelInBanner: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    vsDividerInBanner: {
      alignItems: 'center',
      gap: 4,
      minWidth: 60,
    },
    vsCircleInBanner: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(37,99,235,0.9)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    vsTextInBanner: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '800',
    },
    // VS quick-modal styles
    vsModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.4)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    vsModalCard: {
      width: '86%',
      backgroundColor: Colors[colorScheme].card,
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.12)' }
        : {
            shadowColor: '#000',
            shadowOpacity: 0.12,
            shadowRadius: 10,
            shadowOffset: { width: 0, height: 4 },
          }),
      elevation: 6,
    },
    vsModalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors[colorScheme].text,
      marginBottom: 8,
      textAlign: 'center',
    },
    vsModalBody: { color: Colors[colorScheme].mutedText, textAlign: 'center', marginBottom: 12 },
    vsModalClose: {
      backgroundColor: Colors[colorScheme].tint,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    vsPollRow: { flexDirection: 'row', width: '100%', gap: 8, marginVertical: 8 },
    vsTeamCard: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 10,
      backgroundColor: Colors[colorScheme].surface,
      borderWidth: 1,
      borderColor: Colors[colorScheme].border,
    },
    vsTeamCardOn: {
      backgroundColor: Colors[colorScheme].tint,
      borderColor: Colors[colorScheme].tint,
    },
    vsTeamName: {
      fontWeight: '800',
      color: Colors[colorScheme].text,
      marginBottom: 4,
      textAlign: 'center',
    },
    vsTeamPct: { fontSize: 18, fontWeight: '900', color: Colors[colorScheme].text },
    vsTeamVotes: { fontSize: 12, color: Colors[colorScheme].mutedText, marginTop: 4 },
    vsDivider: { width: 12 },
    vsPctBarWrap: {
      width: '100%',
      height: 8,
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.15)' : 'rgba(37,99,235,0.15)',
      borderRadius: 6,
      overflow: 'hidden',
      marginTop: 8,
    },
    vsPctBarFill: {
      height: '100%',
      backgroundColor: colorScheme === 'dark' ? '#60a5fa' : '#2563eb',
      width: '0%',
    },
    // Posts Grid Styles
    postsGridContainer: {
      marginTop: 12,
    },
    postsMasonryGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    // One scrapbook row: 2 or 3 cells whose widths come from the row plan.
    scrapbookRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    masonryColumn: {
      flex: 1,
      gap: 8,
    },
    masonryItem: {
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: Colors[colorScheme].surface,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
          }),
      elevation: 3,
    },
    postsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: -1.5,
    },
    gridItem: {
      width: '32%',
      aspectRatio: 1,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: Colors[colorScheme].surface,
      marginBottom: '2%',
    },
    gridItemEmpty: {
      backgroundColor: Colors[colorScheme].surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: Colors[colorScheme].border,
    },
    gridImageContainer: {
      width: '100%',
      height: '100%',
    },
    gridImage: { width: '100%', height: '100%' },
    gridImageOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
    gridImageFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 12,
      position: 'relative',
    },
    textPostOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 12,
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderRadius: 8,
      margin: 8,
    },
    gridTextOnly: {
      textAlign: 'center',
      color: '#ffffff',
      fontWeight: '700',
      fontSize: 12,
      lineHeight: 16,
      ...(Platform.OS === 'web'
        ? { textShadow: '0px 1px 2px rgba(0, 0, 0, 0.3)' }
        : {
            textShadowColor: 'rgba(0,0,0,0.3)',
            textShadowOffset: { width: 0, height: 1 },
            textShadowRadius: 2,
          }),
    },
    gridIconBadge: {
      position: 'absolute',
      bottom: 8,
      right: 8,
      backgroundColor: 'rgba(0,0,0,0.6)',
      borderRadius: 14,
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.3)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.3,
            shadowRadius: 2,
          }),
    },
    gridCounts: {
      position: 'absolute',
      left: 8,
      bottom: 8,
      backgroundColor: 'rgba(0,0,0,0.6)',
      borderRadius: 14,
      paddingHorizontal: 8,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.3)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.3,
            shadowRadius: 2,
          }),
    },
    gridCountItem: { flexDirection: 'row', alignItems: 'center', gap: 3 },
    gridCountText: { color: '#fff', fontSize: 10, fontWeight: '700' },
    viewAllPostsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors[colorScheme].surface,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginTop: 16,
    },
    viewAllPostsText: {
      fontSize: 15,
      fontWeight: '600',
      color: Colors[colorScheme].text,
      marginRight: 8,
    },
    loginPromptSheet: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 24,
      paddingBottom: 40,
      gap: 12,
    },
    loginPromptTitle: {
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 4,
    },
    loginPromptBody: {
      fontSize: 15,
      textAlign: 'center',
      marginBottom: 8,
    },
    loginPromptBtn: {
      height: 50,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loginPromptBtnText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    loginPromptCancel: {
      height: 50,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
    },
    loginPromptCancelText: {
      fontSize: 16,
      fontWeight: '600',
    },
  });
