import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  title: { fontSize: 28, fontWeight: '900', marginBottom: 8 },
  center: { paddingVertical: 24, alignItems: 'center' },
  helper: { marginBottom: 10 },
  mutedSmall: { marginBottom: 10, fontSize: 12 },
  noticeText: { fontSize: 13, marginBottom: 4 },
  optionalStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  inlineRetryButton: {
    borderRadius: 8,
    backgroundColor: '#2563EB',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  inlineRetryText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  sectionTitle: { fontWeight: '800', marginTop: 8 },
  browseOrgsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  browseOrgsText: { flex: 1, fontWeight: '600', fontSize: 15 },
  error: { marginBottom: 8 },
  calendarSection: {
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
  },
  searchInput: { flex: 1, height: 44, fontSize: 16 },
  viewToggle: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    marginBottom: 8,
  },
  precisionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  precisionBannerText: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  precisionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  precisionActionLink: {
    fontSize: 13,
  },
  zipSuggestionList: {
    marginTop: 6,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0px 4px 12px rgba(15, 23, 42, 0.08)' }
      : {
          shadowColor: '#0f172a',
          shadowOpacity: 0.08,
          shadowRadius: 12,
          shadowOffset: { width: 0, height: 4 },
        }),
    elevation: 3,
  },
  zipSuggestionItem: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  zipSuggestionZip: { fontWeight: '700', fontSize: 15 },
  zipSuggestionCount: { fontSize: 12 },
  unifiedSearchResults: {
    marginTop: 6,
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
    maxHeight: 360,
  },
  searchSection: { paddingTop: 8 },
  searchSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  searchResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  searchResultLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  searchResultAvatar: { width: 40, height: 40, borderRadius: 20 },
  searchResultName: { fontWeight: '700', fontSize: 15 },
  searchResultSub: { fontSize: 12, marginTop: 1 },
  searchFollowBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  searchFollowBtnText: { fontWeight: '800', fontSize: 13 },
  searchEmpty: { padding: 16, textAlign: 'center', fontSize: 14 },
  followingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    marginTop: 4,
    marginBottom: 10,
  },
  followingText: { fontWeight: '700' },
  followingBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#1D4ED8',
  },
  followingBtnText: { color: 'white', fontWeight: '800' },
  followingCardMuted: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    marginTop: 4,
    marginBottom: 10,
  },
  followingMutedText: { fontWeight: '600' },
  // Segmented tabs
  tabsWrap: {
    flexDirection: 'row',
    borderRadius: 10,
    marginTop: 4,
    marginBottom: 8,
    padding: 4,
    gap: 6,
    height: 40,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  tabOn: {},
  tabLabel: { fontWeight: '700' },
  tabLabelOn: {},
  // Post header (avatar + follow button)
  postHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 6,
  },
  postHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  postAvatarWrap: { width: 28, height: 28, borderRadius: 14, overflow: 'hidden' },
  postAvatar: { width: 28, height: 28, borderRadius: 14 },
  postAuthorName: { fontWeight: '700', maxWidth: 200 },
  followBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  followBtnOn: {},
  followBtnText: { fontWeight: '800' },
  followBtnTextOn: {},
  card: { padding: 14, borderRadius: 14, borderWidth: 1 },
  hero: { height: 140, borderRadius: 12, marginBottom: 12, overflow: 'hidden' },
  heroImage: { width: '100%', height: '100%' },
  cardTitle: { fontWeight: '800', fontSize: 18, marginBottom: 2 },
  cardMeta: {},
  cardContent: { paddingHorizontal: 4, paddingBottom: 8 },
  teamRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  teamPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  teamPillText: { fontWeight: '700' },
  vsText: { marginHorizontal: 4, fontWeight: '800' },
  teamPillAlt: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  teamPillAltText: { fontWeight: '700' },
  personTile: { width: 84, marginRight: 10, alignItems: 'center' },
  personAvatar: { width: 64, height: 64, borderRadius: 32 },
  personName: { marginTop: 6, fontSize: 12, maxWidth: 84 },
  suggestedCard: {
    width: 130,
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.07)',
  },
  suggestedAvatar: { width: 56, height: 56, borderRadius: 28 },
  suggestedName: { marginTop: 8, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  suggestedMeta: { fontSize: 11, marginTop: 2, textAlign: 'center' },
  suggestedFollowBtn: {
    marginTop: 8,
    backgroundColor: '#1e3a5f',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    width: '100%',
    alignItems: 'center',
  },
  suggestedFollowingBtn: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#ccc' },
  suggestedFollowText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  // Coach Dashboard Styles
  coachDashboard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
  },
  coachTitle: {
    fontSize: 20,
    fontWeight: '800',
  },
  coachActionCard: {
    width: 140,
    padding: 12,
    borderRadius: 12,
    marginRight: 12,
    alignItems: 'center',
    borderWidth: 1,
  },
  coachActionTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  coachActionDesc: {
    fontSize: 11,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 14,
  },
  // Section Tabs
  sectionTabBar: {
    borderBottomWidth: 1,
    marginBottom: 8,
  },
  sectionTabContent: {
    flexDirection: 'row',
    paddingHorizontal: 8,
  },
  sectionTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  sectionTabLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  // Selected Date Section
  selectedDateSection: {
    marginBottom: 16,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  selectedDateTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  dateGameCard: {
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
  },
  dateGameTime: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  dateGameTimeText: {
    fontSize: 13,
    fontWeight: '600',
  },
  dateGameTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  dateGameLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dateGameLocationText: {
    fontSize: 12,
  },
});
