import { Platform, StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';
import { Type } from '@/ui/tokens';

export const createStyles = (colorScheme: 'light' | 'dark') =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors[colorScheme].background,
    },
    title: {
      ...(Type.h1 as any),
      color: Colors[colorScheme].text,
      marginBottom: 8,
      textAlign: 'center',
    },
    subtitle: {
      color: Colors[colorScheme].mutedText,
      marginBottom: 16,
      textAlign: 'center',
      fontSize: 16,
    },
    label: {
      fontWeight: '700',
      color: Colors[colorScheme].text,
      marginBottom: 4,
    },
    locationFieldWrapper: {
      position: 'relative',
      marginBottom: 8,
    },
    locationSpinner: {
      position: 'absolute',
      right: 12,
      top: 12,
    },
    locationSuggestionList: {
      marginTop: 6,
      borderWidth: 1,
      borderColor: Colors[colorScheme].border,
      borderRadius: 12,
      backgroundColor: Colors[colorScheme].surface,
      overflow: 'hidden',
    },
    locationSuggestionItem: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderBottomWidth: 1,
      borderBottomColor: Colors[colorScheme].border,
    },
    locationSuggestionItemLast: {
      borderBottomWidth: 0,
    },
    locationSuggestionMain: {
      fontSize: 15,
      fontWeight: '600',
      color: Colors[colorScheme].text,
    },
    locationSuggestionSecondary: {
      fontSize: 13,
      color: Colors[colorScheme].mutedText,
      marginTop: 2,
    },
    inputHelperText: {
      fontSize: 12,
      color: Colors[colorScheme].mutedText,
      marginBottom: 24,
    },
    // Legacy modal styles (kept for reference) replaced by enhanced modal
    enhancedModalOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(15,23,42,0.70)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
      zIndex: 60,
    },
    enhancedModalCard: {
      width: '100%',
      maxWidth: 500,
      backgroundColor: colorScheme === 'dark' ? '#121212' : '#FFFFFF',
      borderRadius: 28,
      paddingHorizontal: 24,
      paddingVertical: 24,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 12px 32px rgba(0, 0, 0, 0.3)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 12 },
            shadowOpacity: 0.3,
            shadowRadius: 32,
          }),
      elevation: 12,
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#3A3A3C' : '#E2E8F0',
    },
    enhancedModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    enhancedModalIconCircle: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colorScheme === 'dark' ? '#0369A1' : '#0284C7',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 6px 12px rgba(2, 132, 199, 0.4)' }
        : {
            shadowColor: '#0284C7',
            shadowOpacity: 0.4,
            shadowOffset: { width: 0, height: 6 },
            shadowRadius: 12,
          }),
    },
    enhancedModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#F8FAFC' : '#0F172A',
      letterSpacing: 0.5,
    },
    enhancedModalOrg: {
      fontSize: 16,
      fontWeight: '500',
      color: colorScheme === 'dark' ? '#94A3B8' : '#475569',
      marginTop: 2,
    },
    closeTouch: {
      padding: 6,
      marginLeft: 4,
      borderRadius: 8,
    },
    enhancedModalLabel: {
      fontSize: 13,
      fontWeight: '600',
      textTransform: 'uppercase',
      marginBottom: 8,
      color: colorScheme === 'dark' ? '#94A3B8' : '#64748B',
      letterSpacing: 0.5,
    },
    textAreaWrapper: {
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#3A3A3C' : '#CBD5E1',
      borderRadius: 16,
      backgroundColor: colorScheme === 'dark' ? '#1E1E1E' : '#F8FAFC',
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 12,
    },
    textArea: {
      minHeight: 100,
      fontSize: 15,
      lineHeight: 20,
      color: colorScheme === 'dark' ? '#F1F5F9' : '#0F172A',
      textAlignVertical: 'top',
    },
    charCountRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 6,
    },
    charCountText: {
      fontSize: 12,
      color: colorScheme === 'dark' ? '#64748B' : '#64748B',
    },
    charLimitWarning: {
      fontSize: 12,
      color: colorScheme === 'dark' ? '#F59E0B' : '#B45309',
    },
    enhancedActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 4,
      marginBottom: 16,
    },
    secondaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 14,
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.05)' : '#F1F5F9',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#3A3A3C' : '#E2E8F0',
    },
    secondaryActionText: {
      fontSize: 14,
      fontWeight: '600',
      color: colorScheme === 'dark' ? '#38BDF8' : '#0369A1',
      marginLeft: 6,
    },
    primaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colorScheme === 'dark' ? '#0284C7' : '#0369A1',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 16,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0px 6px 12px rgba(2, 132, 199, 0.35)' }
        : {
            shadowColor: '#0284C7',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.35,
            shadowRadius: 12,
          }),
      elevation: 6,
    },
    primaryActionText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#fff',
      letterSpacing: 0.3,
    },
    helperInfo: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    helperInfoText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 16,
      color: colorScheme === 'dark' ? '#64748B' : '#64748B',
    },
    successBox: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(16,185,129,0.1)' : '#ECFDF5',
      borderRadius: 16,
      padding: 24,
      alignItems: 'center',
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(16,185,129,0.3)' : '#6EE7B7',
    },
    successTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#34D399' : '#065F46',
      marginBottom: 8,
    },
    successText: {
      fontSize: 15,
      lineHeight: 22,
      textAlign: 'center',
      color: colorScheme === 'dark' ? '#D1FAE5' : '#065F46',
    },
    infoBox: {
      flexDirection: 'row',
      padding: 16,
      borderRadius: 16,
      backgroundColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.08)' : '#EFF6FF',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.3)' : '#BFDBFE',
      marginBottom: 24,
    },
    orgPageCard: {
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#1E3A8A' : '#93C5FD',
      backgroundColor: colorScheme === 'dark' ? 'rgba(30,64,175,0.18)' : '#EFF6FF',
      borderRadius: 16,
      padding: 18,
      marginBottom: 24,
    },
    finalSetupCard: {
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#1D4ED8' : '#93C5FD',
      backgroundColor: colorScheme === 'dark' ? 'rgba(29,78,216,0.18)' : '#EFF6FF',
      borderRadius: 16,
      padding: 18,
      marginBottom: 20,
    },
    finalSetupHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    finalSetupTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#DBEAFE' : '#1E3A8A',
    },
    finalSetupBody: {
      fontSize: 14,
      lineHeight: 20,
      color: colorScheme === 'dark' ? '#BFDBFE' : '#1E3A8A',
      marginBottom: 6,
    },
    finalSetupBodyStrong: {
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#EFF6FF' : '#1E3A8A',
    },
    howItWorksCard: {
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#1E3A8A' : '#93C5FD',
      backgroundColor: colorScheme === 'dark' ? 'rgba(30,64,175,0.15)' : '#F1F8FF',
      borderRadius: 14,
      padding: 16,
      marginBottom: 20,
    },
    howItWorksHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    howItWorksTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#1D4ED8' : '#1D4ED8',
    },
    howItWorksTreeBox: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(29,78,216,0.25)' : '#DBEAFE',
      borderRadius: 8,
      padding: 10,
      marginBottom: 12,
    },
    howItWorksTreeLine: {
      fontSize: 13,
      fontFamily: 'Courier',
      color: colorScheme === 'dark' ? '#BFDBFE' : '#1E3A8A',
    },
    howItWorksDescLine: {
      fontSize: 14,
      lineHeight: 20,
      color: colorScheme === 'dark' ? '#BFDBFE' : '#1E3A8A',
      marginBottom: 4,
    },
    howItWorksDescStrong: {
      fontWeight: '700',
    },
    orgPageHeadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    orgPageTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colorScheme === 'dark' ? '#1D4ED8' : '#0F172A',
    },
    orgPageSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colorScheme === 'dark' ? '#CBD5E1' : '#475569',
    },
    infoIcon: { marginRight: 16 },
    infoContent: { flex: 1 },
    infoTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: Colors[colorScheme].text,
      marginBottom: 4,
    },
    infoText: {
      fontSize: 14,
      lineHeight: 20,
      color: Colors[colorScheme].mutedText,
    },
    selectField: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 16,
      minHeight: 52,
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    selectFieldText: {
      fontSize: 15,
      fontWeight: '500',
      color: colorScheme === 'dark' ? '#E2E8F0' : '#0F172A',
    },
    typeModalOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 70,
      padding: 24,
    },
    typeModalCard: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: colorScheme === 'dark' ? '#121212' : '#FFFFFF',
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#3A3A3C' : '#E2E8F0',
    },
    typeModalTitle: {
      fontSize: 17,
      fontWeight: '700',
      marginBottom: 12,
      color: colorScheme === 'dark' ? '#F1F5F9' : '#0F172A',
    },
    typeOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      marginBottom: 6,
      backgroundColor: colorScheme === 'dark' ? '#1E1E1E' : '#F8FAFC',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#3A3A3C' : '#E2E8F0',
    },
    typeOptionActive: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.25)' : '#DBEAFE',
      borderColor: colorScheme === 'dark' ? '#3B82F6' : '#3B82F6',
    },
    typeOptionText: {
      fontSize: 15,
      fontWeight: '500',
      marginLeft: 8,
      color: colorScheme === 'dark' ? '#E2E8F0' : '#0F172A',
    },
    typeModalActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
    },
    typeCancel: {
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 12,
      backgroundColor: colorScheme === 'dark' ? '#3A3A3C' : '#F1F5F9',
    },
    typeCancelText: {
      fontSize: 15,
      fontWeight: '600',
      color: colorScheme === 'dark' ? '#E2E8F0' : '#0F172A',
    },
    typeConfirm: {
      paddingVertical: 10,
      paddingHorizontal: 22,
      borderRadius: 12,
      backgroundColor: colorScheme === 'dark' ? '#0284C7' : '#0369A1',
    },
    typeConfirmText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#fff',
    },
    searchPrompt: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(59,130,246,0.1)' : '#EFF6FF',
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      alignItems: 'center',
    },
    modeToggleWrapper: {
      marginBottom: 20,
      alignItems: 'center',
    },
    modeToggleBracket: {
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? '#1E3A8A' : '#93C5FD',
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: colorScheme === 'dark' ? 'rgba(30,64,175,0.25)' : '#DBEAFE',
    },
    modeToggleOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 18,
      gap: 6,
    },
    modeToggleOptionActive: {
      backgroundColor: colorScheme === 'dark' ? '#1D4ED8' : '#1D4ED8',
    },
    modeToggleText: {
      fontSize: 14,
      fontWeight: '600',
      color: colorScheme === 'dark' ? '#E2E8F0' : '#0F172A',
    },
    modeToggleTextActive: {
      color: '#FFFFFF',
    },
    searchPromptText: {
      color: Colors[colorScheme].text,
      fontSize: 15,
      marginBottom: 12,
      textAlign: 'center',
    },
    searchButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors[colorScheme].tint,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    searchButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 15,
    },
    dividerText: {
      color: Colors[colorScheme].mutedText,
      fontSize: 14,
      textAlign: 'center',
      marginBottom: 16,
      fontStyle: 'italic',
    },
    searchBox: {
      flex: 1,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    backButtonText: {
      color: Colors[colorScheme].tint,
      fontSize: 15,
      fontWeight: '600',
    },
    searchActionButton: {
      backgroundColor: Colors[colorScheme].tint,
      width: 48,
      height: 48,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    orgList: {
      maxHeight: 400,
    },
    searchEmptyState: {
      borderWidth: 1,
      borderRadius: 12,
      padding: 16,
      gap: 8,
    },
    searchEmptyTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: Colors[colorScheme].text,
    },
    searchEmptyText: {
      fontSize: 14,
      lineHeight: 20,
      color: Colors[colorScheme].mutedText,
    },
    resultsHeader: {
      fontSize: 15,
      fontWeight: '600',
      color: Colors[colorScheme].text,
      marginBottom: 12,
    },
    pickerContainer: {
      borderWidth: 1,
      borderRadius: 8,
      overflow: 'hidden',
      marginBottom: 12,
    },
    picker: {
      height: 50,
    },
    orgCard: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.05)' : '#fff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.1)' : '#D1D5DB',
    },
    orgCardContent: {
      marginBottom: 12,
    },
    orgCardName: {
      fontSize: 17,
      fontWeight: '700',
      color: Colors[colorScheme].text,
      marginBottom: 4,
    },
    orgCardLocation: {
      fontSize: 14,
      color: Colors[colorScheme].mutedText,
      marginBottom: 4,
    },
    orgCardSport: {
      fontSize: 14,
      color: Colors[colorScheme].mutedText,
      marginBottom: 4,
    },
    orgCardMeta: {
      fontSize: 13,
      color: Colors[colorScheme].mutedText,
    },
    joinButton: {
      backgroundColor: '#22c55e',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: 'center',
    },
    joinButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 15,
    },
    modal: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      zIndex: 1000,
    },
    modalContent: {
      backgroundColor: Colors[colorScheme].background,
      borderRadius: 16,
      padding: 24,
      width: '100%',
      maxWidth: 400,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: Colors[colorScheme].text,
      marginBottom: 4,
    },
    modalSubtitle: {
      fontSize: 16,
      color: Colors[colorScheme].mutedText,
      marginBottom: 20,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalButtonCancel: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.1)' : '#F3F4F6',
    },
    modalButtonSubmit: {
      backgroundColor: Colors[colorScheme].tint,
    },
    modalButtonTextCancel: {
      color: Colors[colorScheme].text,
      fontWeight: '600',
      fontSize: 16,
    },
    modalButtonTextSubmit: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 16,
    },
    duplicateWarningBox: {
      flexDirection: 'column',
      backgroundColor: colorScheme === 'dark' ? 'rgba(245, 158, 11, 0.15)' : '#FEF3C7',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: colorScheme === 'dark' ? 'rgba(245, 158, 11, 0.3)' : '#FDE68A',
    },
    duplicateWarningText: {
      fontSize: 13,
      color: colorScheme === 'dark' ? '#FCD34D' : '#92400E',
      lineHeight: 18,
    },
    duplicateJoinButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colorScheme === 'dark' ? '#1D4ED8' : '#2563EB',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 6,
    },
    duplicateJoinButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '600',
    },
    duplicateCreateAnywayText: {
      fontSize: 13,
      color: colorScheme === 'dark' ? '#94A3B8' : '#64748B',
      textDecorationLine: 'underline',
    },
  });
